# Generated by Django 2.2.3 on 2020-08-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0004_auto_20200816_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=models.SET(0), to='usersmanage.User', verbose_name='Покупатель'),
        ),
    ]
